CREATE TABLE USER (
  ID       INT AUTO_INCREMENT PRIMARY KEY,
  LOGIN    VARCHAR(255),
  PASSWORD VARCHAR(32),
  SALT     VARCHAR(32),
  CONSTRAINT UNIQUE_USER_LOGIN UNIQUE (LOGIN)
);

CREATE TABLE RESOURCE_USERS_ROLES (
  ID      INT AUTO_INCREMENT PRIMARY KEY,
  USER_ID INT,
  ROLE    VARCHAR(10),
  PATH    VARCHAR(255),
  CONSTRAINT FK_RUR_USER_ID FOREIGN KEY (USER_ID)
  REFERENCES USER (ID)
);

CREATE INDEX IDX_ROLE
  ON RESOURCE_USERS_ROLES (USER_ID);

CREATE TABLE ACCOUNTING (
  ID                      INT AUTO_INCREMENT PRIMARY KEY,
  LOGIN                   VARCHAR(255),
  ROLE                    VARCHAR(10),
  PATH                    VARCHAR(255),
  RESOURCE_USERS_ROLES_ID INT,
  START_DATE              DATE,
  END_DATE                DATE,
  VOLUME                  INT,
  CONSTRAINT FK_ACC_RESOURCE_USERS_ROLES_ID
  FOREIGN KEY (RESOURCE_USERS_ROLES_ID)
  REFERENCES RESOURCE_USERS_ROLES (ID)
);